title:              Qiong's Blog
email:              qiongru.liang@gmail.com
description:        The bigger the why, the easier the how
author:             Dilys Qiong
baseurl:            "/"
url:                "https://dilysqiong.github.io/"

# Social Profiles
twitter_username:   DilysQiong
github_username:    DilysQiong
facebook_username:  DilysQiong
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
